"use client";

import { useState, useEffect, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getPacientes, getMedidasByPaciente, deleteMedida, saveMedidas } from "@/lib/storage";
import { saveEvaluation } from "@/actions/anthropometry-actions";
import { createPatient } from "@/actions/patient-actions";
import { calculateBodyComposition } from "@/lib/bodyCompositionMath";
import { useToast } from "@/hooks/use-toast";
import { AntropometriaLayout } from "@/components/antropometria/AntropometriaLayout";
import { FullMeasurementData } from "@/components/antropometria/UnifiedMeasurementForm";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PlusCircle, Search, Users, ArrowRight, BookOpen, Activity, Save, RotateCcw } from "lucide-react";
import type { Paciente, MedidasAntropometricas } from "@/types";
import { useAuthStore } from "@/store/useAuthStore";

function AntropometriaContent() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const { user } = useAuthStore();

    const [pacientes, setPacientes] = useState<Paciente[]>([]);
    const [selectedPacienteId, setSelectedPacienteId] = useState<string | null>(null);
    const [medidas, setMedidas] = useState<MedidasAntropometricas[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [patientSearch, setPatientSearch] = useState("");

    // Filter patients based on search
    const filteredPatients = pacientes.filter(p => {
        if (!patientSearch) return true;
        const fullName = `${p.datosPersonales.nombre} ${p.datosPersonales.apellido}`.toLowerCase();
        return fullName.includes(patientSearch.toLowerCase());
    });

    useEffect(() => {
        if (user) {
            const data = getPacientes(user.id);
            setPacientes(data);
            const paramId = searchParams.get("id");
            if (paramId) setSelectedPacienteId(paramId);
        }
        setIsLoading(false);
    }, [user, searchParams]);

    useEffect(() => {
        if (selectedPacienteId) {
            setMedidas(getMedidasByPaciente(selectedPacienteId));
        } else {
            setMedidas([]);
        }
    }, [selectedPacienteId]);

    const handlePacienteChange = (id: string) => {
        setSelectedPacienteId(id);
        window.history.pushState({}, "", `?id=${id}`);
    };

    const { toast } = useToast();

    // ... (rest of hook calls)

    const handleSave = async (data: FullMeasurementData) => {
        if (!selectedPacienteId || !user) return;

        setIsLoading(true);

        // 1. Calculate Results Snapshot (Basic Body Composition)
        // Note: Somatotype calculation is skipped for snapshot as the logic is tied to the UI component.
        // It will be calculated on-the-fly when viewing the record.
        const skinfoldData = {
            triceps: data.skinfolds.triceps,
            subscapular: data.skinfolds.subscapular,
            biceps: data.skinfolds.biceps,
            iliac_crest: data.skinfolds.iliac_crest,
            supraspinale: data.skinfolds.supraspinale,
            abdominal: data.skinfolds.abdominal,
            thigh: data.skinfolds.thigh,
            calf: data.skinfolds.calf
        };

        // Use 'general' formula as default for snapshot if not specified, 
        // or check if we can infer it. For now, use 'general'.
        const composition = calculateBodyComposition('general', data.bioData.genero === 'masculino' ? 'male' : 'female', skinfoldData, data.bioData.peso);

        // 2. Calculate IMC
        const tallaMetros = data.bioData.talla / 100;
        const imc = tallaMetros > 0 ? data.bioData.peso / (tallaMetros * tallaMetros) : 0;

        // 3. Map Data
        const nuevaMedida: MedidasAntropometricas = {
            id: '', // Generated by DB
            pacienteId: selectedPacienteId,
            fecha: new Date().toISOString(),
            tipoPaciente: 'general',
            peso: data.bioData.peso,
            talla: data.bioData.talla,
            edad: data.bioData.edad,
            sexo: data.bioData.genero,
            imc: Math.round(imc * 100) / 100, // IMC with 2 decimals
            pliegues: {
                triceps: data.skinfolds.triceps,
                biceps: data.skinfolds.biceps,
                subscapular: data.skinfolds.subscapular,
                supraspinale: data.skinfolds.supraspinale,
                // iliac_crest: data.skinfolds.iliac_crest, // NOTE: MedidasAntropometricas type might rely on 'supraspinale' or 'iliac_crest' depending on ISAK version. 
                // Let's use what we have in types.ts. types.ts has 'iliac_crest' AND 'supraspinale'.
                iliac_crest: data.skinfolds.iliac_crest,
                abdominal: data.skinfolds.abdominal,
                thigh: data.skinfolds.thigh,
                calf: data.skinfolds.calf
            },
            perimetros: {
                brazoRelajado: data.girths.brazoRelajado,
                brazoFlex: data.girths.brazoFlexionado,
                cintura: data.girths.cintura,
                pantorrilla: data.girths.pantorrilla,
                cadera: undefined, // Add if available
                musloMedio: undefined // Add if available
            },
            diametros: {
                humero: data.breadths.humero,
                femur: data.breadths.femur
            }
        };

        // 2.5 Ensure Patient Exists in DB (Sync on demand)
        if (selectedPaciente) {
            console.log("🔄 Asegurando sincronización de paciente:", selectedPacienteId);
            await createPatient(selectedPaciente);
        }

        // 2.6 Generate ID for localStorage and save locally FIRST
        const medidasConId: MedidasAntropometricas = {
            ...nuevaMedida,
            id: crypto.randomUUID() // Generate a client-side ID
        };

        // 3. Save to localStorage FIRST (for immediate UI update)
        saveMedidas(medidasConId);
        console.log("✅ Medidas guardadas en localStorage:", medidasConId.id);

        // 4. Sync to Database (background save)
        const result = await saveEvaluation(medidasConId, {
            bodyFatPercent: composition.isValid ? composition.fatPercent : undefined,
            muscleMassKg: composition.isValid ? composition.leanMassKg : undefined
        });

        if (result.success) {
            toast({
                title: "Evaluación Guardada",
                description: "Los datos se han registrado correctamente en el historial.",
                variant: "default",
                className: "bg-green-500 text-white border-none"
            });

            // Redirect to Patient Profile -> Evolution Tab
            if (selectedPacienteId) {
                router.push(`/pacientes/${selectedPacienteId}?tab=avance`);
            }
        } else {
            toast({
                title: "Error al guardar",
                description: result.error || "No se pudo registrar la evaluación.",
                variant: "destructive"
            });
        }

        setIsLoading(false);
    };

    const handleDeleteMedida = (id: string) => {
        deleteMedida(id);
        if (selectedPacienteId) {
            setMedidas(getMedidasByPaciente(selectedPacienteId));
        }
    };

    const selectedPaciente = pacientes.find(p => p.id === selectedPacienteId);

    // Obtener la última medida del paciente (más reciente primero)
    const ultimaMedida = medidas.length > 0 ? medidas[0] : null;

    if (isLoading) {
        return (
            <div className="flex items-center justify-center h-screen">
                <Activity className="w-10 h-10 text-[#ff8508] animate-pulse" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-white dark:bg-[#0f172a]">
            {/* NEW HEADER DESIGN */}
            <div className="border-b border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 sticky top-0 z-30">
                <div className="container mx-auto px-4 md:px-6 py-4 md:py-0 md:h-20 flex flex-col md:flex-row md:items-center justify-between gap-4 max-w-[1600px]">

                    {/* LEFT: Title & Subtitle */}
                    <div className="flex flex-col">
                        <h1 className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
                            Evaluación <span className="text-[#ff8508]">Antropométrica</span>
                        </h1>
                        <p className="text-sm text-slate-400">
                            Evaluación paso a paso
                        </p>
                    </div>

                    {/* RIGHT: Controls */}
                    <div className="flex flex-wrap items-center gap-2 md:gap-3 w-full md:w-auto">
                        {/* Patient Search Input */}
                        {!selectedPaciente ? (
                            <div className="w-full md:w-[300px] relative">
                                <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
                                <input
                                    type="text"
                                    placeholder="Buscar paciente..."
                                    className="w-full h-11 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl shadow-sm hover:border-[#ff8508] transition-colors focus:ring-[#ff8508] focus:border-[#ff8508] pl-10 pr-4 text-slate-600 dark:text-slate-300 outline-none"
                                    value={patientSearch}
                                    onChange={(e) => setPatientSearch(e.target.value)}
                                />
                            </div>
                        ) : (
                            <div className="flex items-center gap-2 px-4 py-2 bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
                                <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">
                                    {selectedPaciente.datosPersonales.nombre} {selectedPaciente.datosPersonales.apellido}
                                </span>
                                <Button variant="ghost" size="icon" className="h-6 w-6 ml-2 text-slate-400 hover:text-red-500" onClick={() => setSelectedPacienteId(null)}>
                                    <RotateCcw className="w-3 h-3" />
                                </Button>
                            </div>
                        )}

                        <div className="h-8 w-px bg-slate-200 dark:bg-slate-700 mx-2" />

                        <Button
                            variant="outline"
                            className="h-11 rounded-xl border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 gap-2 font-medium"
                            onClick={() => router.push('/antropometria/formulas')}
                        >
                            <BookOpen className="w-4 h-4" /> Formulas
                        </Button>

                        <Button
                            variant="secondary"
                            size="icon"
                            className="h-11 w-11 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700"
                            onClick={() => router.push('/pacientes/nuevo')}
                        >
                            <PlusCircle className="w-5 h-5" />
                        </Button>
                    </div>
                </div>
            </div>

            <div className="container mx-auto p-4 md:p-6 max-w-[1600px]">
                {!selectedPaciente ? (
                    // CHECK IF THERE ARE PATIENTS
                    pacientes.length > 0 ? (
                        // PATIENT DIRECTORY - Show list of patients to select
                        <div className="animate-in fade-in duration-300">
                            <div className="mb-4 flex items-center justify-between">
                                <h2 className="text-lg font-semibold text-slate-800 dark:text-white">
                                    Directorio de Pacientes
                                    <span className="ml-2 text-sm font-normal text-slate-400">
                                        ({filteredPatients.length} {filteredPatients.length === 1 ? 'paciente' : 'pacientes'})
                                    </span>
                                </h2>
                                {patientSearch && (
                                    <Button variant="ghost" size="sm" onClick={() => setPatientSearch("")}>
                                        Limpiar búsqueda
                                    </Button>
                                )}
                            </div>
                            <div className="grid gap-3">
                                {filteredPatients.length === 0 ? (
                                    <div className="p-8 border rounded-xl bg-slate-50 dark:bg-slate-800 dark:border-slate-700 text-center text-muted-foreground">
                                        No se encontraron pacientes con "{patientSearch}".
                                    </div>
                                ) : (
                                    filteredPatients.map(p => (
                                        <div
                                            key={p.id}
                                            className="group flex items-center justify-between p-4 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl hover:border-[#ff8508]/50 hover:shadow-md transition-all cursor-pointer"
                                            onClick={() => handlePacienteChange(p.id)}
                                        >
                                            <div className="flex items-center gap-4">
                                                <div className="h-12 w-12 rounded-full bg-[#ff8508]/10 flex items-center justify-center">
                                                    <span className="text-[#ff8508] font-bold text-lg">
                                                        {p.datosPersonales.nombre[0]}{p.datosPersonales.apellido[0]}
                                                    </span>
                                                </div>
                                                <div>
                                                    <h3 className="font-semibold text-slate-800 dark:text-white group-hover:text-[#ff8508] transition-colors">
                                                        {p.datosPersonales.nombre} {p.datosPersonales.apellido}
                                                    </h3>
                                                    <span className="text-xs text-muted-foreground">{p.datosPersonales.email || "Sin email"}</span>
                                                </div>
                                            </div>
                                            <div className="h-8 w-8 rounded-full bg-slate-50 dark:bg-slate-700 group-hover:bg-[#ff8508]/10 flex items-center justify-center transition-colors">
                                                <ArrowRight className="w-4 h-4 text-slate-400 group-hover:text-[#ff8508]" />
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>
                        </div>
                    ) : (
                        // EMPTY STATE - NO PATIENTS REGISTERED
                        <div className="flex flex-col items-center justify-center min-h-[70vh] animate-in fade-in zoom-in-95 duration-500">

                            {/* ICON CLUSTER */}
                            <div className="relative mb-8">
                                <div className="w-24 h-24 bg-[#fff7ed] dark:bg-[#fff7ed]/10 rounded-[2rem] flex items-center justify-center mb-4 text-[#ff8508]">
                                    <Users className="w-10 h-10" />
                                </div>
                                <div className="absolute -bottom-2 -right-2 bg-[#6cba00] p-2 rounded-full border-4 border-white dark:border-[#0f172a]">
                                    <Activity className="w-5 h-5 text-white" />
                                </div>
                            </div>

                            {/* TEXT CONTENT */}
                            <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-3 text-center">
                                No hay pacientes registrados
                            </h2>
                            <p className="text-slate-500 dark:text-slate-400 text-center max-w-md mb-8 leading-relaxed">
                                Para iniciar una evaluación antropométrica, primero debes registrar un paciente en el sistema.
                            </p>

                            {/* ACTION BUTTON */}
                            <Button
                                className="h-12 px-8 rounded-full bg-[#ff8508] hover:bg-[#e67600] text-white font-semibold gap-2 shadow-sm"
                                onClick={() => router.push('/pacientes/nuevo')}
                            >
                                <PlusCircle className="w-4 h-4" /> Agregar Paciente
                            </Button>

                        </div>
                    )
                ) : (
                    // ACTIVE CONTENT
                    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                        {/* We already show the selected patient in header, but keeping the layout consistent with previous content */}
                        <div className="mb-6">
                            <AntropometriaLayout
                                key={`${selectedPacienteId}-${medidas.length}`}
                                patientName={`${selectedPaciente.datosPersonales.nombre} ${selectedPaciente.datosPersonales.apellido}`}
                                patientGender={selectedPaciente.datosPersonales.sexo === 'femenino' ? 'femenino' : 'masculino'}
                                patientBirthDate={typeof selectedPaciente.datosPersonales.fechaNacimiento === 'string'
                                    ? selectedPaciente.datosPersonales.fechaNacimiento
                                    : selectedPaciente.datosPersonales.fechaNacimiento?.toISOString?.() || ''}
                                initialWeight={ultimaMedida?.peso || 0}
                                initialHeight={ultimaMedida?.talla || 0}
                                medidas={medidas}
                                onSave={handleSave}
                                onDeleteMedida={handleDeleteMedida}
                            />
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

export default function AntropometriaPage() {
    return (
        <Suspense fallback={
            <div className="flex items-center justify-center h-screen">
                <Activity className="w-8 h-8 text-[#ff8508] animate-spin" />
            </div>
        }>
            <AntropometriaContent />
        </Suspense>
    );
}